---
# tasks file for nginx-port-switch

- name: Update Nginx port to 81
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  become: true
  notify:
    - Restart Nginx

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
