name: Github Action Workflow
run-name: Terraform Provisioning 

on: 
  push:
    branches: ["main"]

permissions:
  id-token: write

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

  
      - name: Checkout repository code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Apply 
        run: |
          terraform init
          terraform validate 
          terraform apply -auto-approve
        working-directory: ./terraform